/* apps/progs.h */
/* automatically generated by progs.pl for openssl.c */

#define FUNC_TYPE_NONE		0
#define FUNC_TYPE_GENERAL	1
#define FUNC_TYPE_MD		2
#define FUNC_TYPE_CIPHER	3
#define FUNC_TYPE_PKEY		4
#define FUNC_TYPE_MD_ALG	5
#define FUNC_TYPE_CIPHER_ALG	6

typedef struct function_st {
	int type;
	const char *name;
	int (*func)(int argc,char *argv[]);
	const char **help;
} FUNCTION;

#ifndef APP_MAIN
extern FUNCTION functions[];
#endif
extern int verify_main(int argc,char *argv[]);
extern const char *verify_help[];
extern int asn1parse_main(int argc,char *argv[]);
extern const char *asn1parse_help[];
extern int req_main(int argc,char *argv[]);
extern const char *req_help[];
extern int dgst_main(int argc,char *argv[]);
extern const char *dgst_help[];
extern int dh_main(int argc,char *argv[]);
extern const char *dh_help[];
extern int dhparam_main(int argc,char *argv[]);
extern const char *dhparam_help[];
extern int enc_main(int argc,char *argv[]);
extern const char *enc_help[];
extern int passwd_main(int argc,char *argv[]);
extern const char *passwd_help[];
extern int gendh_main(int argc,char *argv[]);
extern const char *gendh_help[];
extern int errstr_main(int argc,char *argv[]);
extern const char *errstr_help[];
extern int ca_main(int argc,char *argv[]);
extern const char *ca_help[];
extern int crl_main(int argc,char *argv[]);
extern const char *crl_help[];
extern int rsa_main(int argc,char *argv[]);
extern const char *rsa_help[];
extern int rsautl_main(int argc,char *argv[]);
extern const char *rsautl_help[];
extern int dsa_main(int argc,char *argv[]);
extern const char *dsa_help[];
extern int dsaparam_main(int argc,char *argv[]);
extern const char *dsaparam_help[];
extern int ec_main(int argc,char *argv[]);
extern const char *ec_help[];
extern int ecparam_main(int argc,char *argv[]);
extern const char *ecparam_help[];
extern int x509_main(int argc,char *argv[]);
extern const char *x509_help[];
extern int genrsa_main(int argc,char *argv[]);
extern const char *genrsa_help[];
extern int gendsa_main(int argc,char *argv[]);
extern const char *gendsa_help[];
extern int genpkey_main(int argc,char *argv[]);
extern const char *genpkey_help[];
extern int s_server_main(int argc,char *argv[]);
extern const char *s_server_help[];
extern int s_client_main(int argc,char *argv[]);
extern const char *s_client_help[];
extern int speed_main(int argc,char *argv[]);
extern const char *speed_help[];
extern int s_time_main(int argc,char *argv[]);
extern const char *s_time_help[];
extern int version_main(int argc,char *argv[]);
extern const char *version_help[];
extern int pkcs7_main(int argc,char *argv[]);
extern const char *pkcs7_help[];
extern int cms_main(int argc,char *argv[]);
extern const char *cms_help[];
extern int crl2pkcs7_main(int argc,char *argv[]);
extern const char *crl2pkcs7_help[];
extern int sess_id_main(int argc,char *argv[]);
extern const char *sess_id_help[];
extern int ciphers_main(int argc,char *argv[]);
extern const char *ciphers_help[];
extern int nseq_main(int argc,char *argv[]);
extern const char *nseq_help[];
extern int pkcs12_main(int argc,char *argv[]);
extern const char *pkcs12_help[];
extern int pkcs8_main(int argc,char *argv[]);
extern const char *pkcs8_help[];
extern int pkey_main(int argc,char *argv[]);
extern const char *pkey_help[];
extern int pkeyparam_main(int argc,char *argv[]);
extern const char *pkeyparam_help[];
extern int pkeyutl_main(int argc,char *argv[]);
extern const char *pkeyutl_help[];
extern int spkac_main(int argc,char *argv[]);
extern const char *spkac_help[];
extern int smime_main(int argc,char *argv[]);
extern const char *smime_help[];
extern int rand_main(int argc,char *argv[]);
extern const char *rand_help[];
extern int engine_main(int argc,char *argv[]);
extern const char *engine_help[];
extern int ocsp_main(int argc,char *argv[]);
extern const char *ocsp_help[];
extern int prime_main(int argc,char *argv[]);
extern const char *prime_help[];
extern int ts_main(int argc,char *argv[]);
extern const char *ts_help[];
extern int srp_main(int argc,char *argv[]);
extern const char *srp_help[];

#ifdef APP_MAIN
FUNCTION functions[] = {
	{ FUNC_TYPE_GENERAL, "verify", verify_main, verify_help },
	{ FUNC_TYPE_GENERAL, "asn1parse", asn1parse_main, asn1parse_help },
	{ FUNC_TYPE_GENERAL, "req", req_main, req_help },
	{ FUNC_TYPE_GENERAL, "dgst", dgst_main, dgst_help },
#ifndef OPENSSL_NO_DH
	{ FUNC_TYPE_GENERAL, "dh", dh_main, dh_help },
#endif
#ifndef OPENSSL_NO_DH
	{ FUNC_TYPE_GENERAL, "dhparam", dhparam_main, dhparam_help },
#endif
	{ FUNC_TYPE_GENERAL, "enc", enc_main, enc_help },
	{ FUNC_TYPE_GENERAL, "passwd", passwd_main, passwd_help },
#ifndef OPENSSL_NO_DH
	{ FUNC_TYPE_GENERAL, "gendh", gendh_main, gendh_help },
#endif
	{ FUNC_TYPE_GENERAL, "errstr", errstr_main, errstr_help },
	{ FUNC_TYPE_GENERAL, "ca", ca_main, ca_help },
	{ FUNC_TYPE_GENERAL, "crl", crl_main, crl_help },
#ifndef OPENSSL_NO_RSA
	{ FUNC_TYPE_GENERAL, "rsa", rsa_main, rsa_help },
#endif
#ifndef OPENSSL_NO_RSA
	{ FUNC_TYPE_GENERAL, "rsautl", rsautl_main, rsautl_help },
#endif
#ifndef OPENSSL_NO_DSA
	{ FUNC_TYPE_GENERAL, "dsa", dsa_main, dsa_help },
#endif
#ifndef OPENSSL_NO_DSA
	{ FUNC_TYPE_GENERAL, "dsaparam", dsaparam_main, dsaparam_help },
#endif
#ifndef OPENSSL_NO_EC
	{ FUNC_TYPE_GENERAL, "ec", ec_main, ec_help },
#endif
#ifndef OPENSSL_NO_EC
	{ FUNC_TYPE_GENERAL, "ecparam", ecparam_main, ecparam_help },
#endif
	{ FUNC_TYPE_GENERAL, "x509", x509_main, x509_help },
#ifndef OPENSSL_NO_RSA
	{ FUNC_TYPE_GENERAL, "genrsa", genrsa_main, genrsa_help },
#endif
#ifndef OPENSSL_NO_DSA
	{ FUNC_TYPE_GENERAL, "gendsa", gendsa_main, gendsa_help },
#endif
	{ FUNC_TYPE_GENERAL, "genpkey", genpkey_main, genpkey_help },
#if !defined(OPENSSL_NO_SOCK)
	{ FUNC_TYPE_GENERAL, "s_server", s_server_main, s_server_help },
#endif
#if !defined(OPENSSL_NO_SOCK)
	{ FUNC_TYPE_GENERAL, "s_client", s_client_main, s_client_help },
#endif
#ifndef OPENSSL_NO_SPEED
	{ FUNC_TYPE_GENERAL, "speed", speed_main, speed_help },
#endif
#if !defined(OPENSSL_NO_SOCK)
	{ FUNC_TYPE_GENERAL, "s_time", s_time_main, s_time_help },
#endif
	{ FUNC_TYPE_GENERAL, "version", version_main, version_help },
	{ FUNC_TYPE_GENERAL, "pkcs7", pkcs7_main, pkcs7_help },
#ifndef OPENSSL_NO_CMS
	{ FUNC_TYPE_GENERAL, "cms", cms_main, cms_help },
#endif
	{ FUNC_TYPE_GENERAL, "crl2pkcs7", crl2pkcs7_main, crl2pkcs7_help },
	{ FUNC_TYPE_GENERAL, "sess_id", sess_id_main, sess_id_help },
#if !defined(OPENSSL_NO_SOCK)
	{ FUNC_TYPE_GENERAL, "ciphers", ciphers_main, ciphers_help },
#endif
	{ FUNC_TYPE_GENERAL, "nseq", nseq_main, nseq_help },
#if !defined(OPENSSL_NO_DES) && !defined(OPENSSL_NO_SHA1)
	{ FUNC_TYPE_GENERAL, "pkcs12", pkcs12_main, pkcs12_help },
#endif
	{ FUNC_TYPE_GENERAL, "pkcs8", pkcs8_main, pkcs8_help },
	{ FUNC_TYPE_GENERAL, "pkey", pkey_main, pkey_help },
	{ FUNC_TYPE_GENERAL, "pkeyparam", pkeyparam_main, pkeyparam_help },
	{ FUNC_TYPE_GENERAL, "pkeyutl", pkeyutl_main, pkeyutl_help },
	{ FUNC_TYPE_GENERAL, "spkac", spkac_main, spkac_help },
	{ FUNC_TYPE_GENERAL, "smime", smime_main, smime_help },
	{ FUNC_TYPE_GENERAL, "rand", rand_main, rand_help },
#ifndef OPENSSL_NO_ENGINE
	{ FUNC_TYPE_GENERAL, "engine", engine_main, engine_help },
#endif
#ifndef OPENSSL_NO_OCSP
	{ FUNC_TYPE_GENERAL, "ocsp", ocsp_main, ocsp_help },
#endif
	{ FUNC_TYPE_GENERAL, "prime", prime_main, prime_help },
	{ FUNC_TYPE_GENERAL, "ts", ts_main, ts_help },
#ifndef OPENSSL_NO_SRP
	{ FUNC_TYPE_GENERAL, "srp", srp_main, srp_help },
#endif
#ifndef OPENSSL_NO_MD2
	{ FUNC_TYPE_MD, "md2", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_MD4
	{ FUNC_TYPE_MD, "md4", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_MD5
	{ FUNC_TYPE_MD, "md5", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_MD_GHOST94
	{ FUNC_TYPE_MD, "md_ghost94", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_SHA
	{ FUNC_TYPE_MD, "sha", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_SHA1
	{ FUNC_TYPE_MD, "sha1", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_SHA224
	{ FUNC_TYPE_MD, "sha224", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_SHA256
	{ FUNC_TYPE_MD, "sha256", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_SHA384
	{ FUNC_TYPE_MD, "sha384", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_SHA512
	{ FUNC_TYPE_MD, "sha512", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_MDC2
	{ FUNC_TYPE_MD, "mdc2", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_RMD160
	{ FUNC_TYPE_MD, "rmd160", dgst_main, dgst_help },
#endif
#ifndef OPENSSL_NO_AES
	{ FUNC_TYPE_CIPHER, "aes-128-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_AES
	{ FUNC_TYPE_CIPHER, "aes-128-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_AES
	{ FUNC_TYPE_CIPHER, "aes-192-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_AES
	{ FUNC_TYPE_CIPHER, "aes-192-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_AES
	{ FUNC_TYPE_CIPHER, "aes-256-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_AES
	{ FUNC_TYPE_CIPHER, "aes-256-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAMELLIA
	{ FUNC_TYPE_CIPHER, "camellia-128-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAMELLIA
	{ FUNC_TYPE_CIPHER, "camellia-128-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAMELLIA
	{ FUNC_TYPE_CIPHER, "camellia-192-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAMELLIA
	{ FUNC_TYPE_CIPHER, "camellia-192-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAMELLIA
	{ FUNC_TYPE_CIPHER, "camellia-256-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAMELLIA
	{ FUNC_TYPE_CIPHER, "camellia-256-ecb", enc_main, enc_help },
#endif
	{ FUNC_TYPE_CIPHER, "base64", enc_main, enc_help },
#ifdef ZLIB
	{ FUNC_TYPE_CIPHER, "zlib", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des3", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "desx", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_IDEA
	{ FUNC_TYPE_CIPHER, "idea", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_SEED
	{ FUNC_TYPE_CIPHER, "seed", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC4
	{ FUNC_TYPE_CIPHER, "rc4", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC4
	{ FUNC_TYPE_CIPHER, "rc4-40", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC2
	{ FUNC_TYPE_CIPHER, "rc2", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_BF
	{ FUNC_TYPE_CIPHER, "bf", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAST
	{ FUNC_TYPE_CIPHER, "cast", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC5
	{ FUNC_TYPE_CIPHER, "rc5", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ede", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ede3", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ede-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ede3-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ede-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ede3-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ofb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ede-ofb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_DES
	{ FUNC_TYPE_CIPHER, "des-ede3-ofb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_IDEA
	{ FUNC_TYPE_CIPHER, "idea-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_IDEA
	{ FUNC_TYPE_CIPHER, "idea-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_IDEA
	{ FUNC_TYPE_CIPHER, "idea-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_IDEA
	{ FUNC_TYPE_CIPHER, "idea-ofb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_SEED
	{ FUNC_TYPE_CIPHER, "seed-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_SEED
	{ FUNC_TYPE_CIPHER, "seed-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_SEED
	{ FUNC_TYPE_CIPHER, "seed-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_SEED
	{ FUNC_TYPE_CIPHER, "seed-ofb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC2
	{ FUNC_TYPE_CIPHER, "rc2-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC2
	{ FUNC_TYPE_CIPHER, "rc2-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC2
	{ FUNC_TYPE_CIPHER, "rc2-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC2
	{ FUNC_TYPE_CIPHER, "rc2-ofb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC2
	{ FUNC_TYPE_CIPHER, "rc2-64-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC2
	{ FUNC_TYPE_CIPHER, "rc2-40-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_BF
	{ FUNC_TYPE_CIPHER, "bf-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_BF
	{ FUNC_TYPE_CIPHER, "bf-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_BF
	{ FUNC_TYPE_CIPHER, "bf-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_BF
	{ FUNC_TYPE_CIPHER, "bf-ofb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAST
	{ FUNC_TYPE_CIPHER, "cast5-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAST
	{ FUNC_TYPE_CIPHER, "cast5-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAST
	{ FUNC_TYPE_CIPHER, "cast5-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAST
	{ FUNC_TYPE_CIPHER, "cast5-ofb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_CAST
	{ FUNC_TYPE_CIPHER, "cast-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC5
	{ FUNC_TYPE_CIPHER, "rc5-cbc", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC5
	{ FUNC_TYPE_CIPHER, "rc5-ecb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC5
	{ FUNC_TYPE_CIPHER, "rc5-cfb", enc_main, enc_help },
#endif
#ifndef OPENSSL_NO_RC5
	{ FUNC_TYPE_CIPHER, "rc5-ofb", enc_main, enc_help },
#endif
	{0,NULL}
	};
#endif
